name: ricette_del_mondo
description: Ricette del Mondo — app di ricette e viaggio culinario.
publish_to: "none"
version: 6.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  share_plus: ^11.1.0
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/logo_rdm.png
    - assets/recipes.json
    - assets/images/
    - assets/banners/
    - assets/splash_v6.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
